### ISSUE TITLE
Обновление со старого mboot

### ISSUE THREAD

**Issue by ya-mouse** [RC-MODULE/MB77.07-firmware-packer#1]
На свежекупленном MB77.07 был прошит:
> mboot-00043-ga4d93ca-dirty (Built Mon Sep 16 11:15:27 MSK 2013)

Соответственно, стандартный способ прошивки не работает. Просто уходит в вечный цикл ожидания, а прошивка (mboot-ued.bin) так и не запускается.
Пришлось обновить вручную:
```
tftpboot 0x40100000 192.168.20.1:mboot-signed.bin
mtd scrub 0x0 0x80000
mtd write 0x40100000 0x0 0x40000
```
После этого всё заработало как в инструкции (я на всякий случай исключил блок с загрузкой mboot-ued и обновлением mboot-signed).

**Comment by nekromant** [comment]
Стандартный способ прошивки с замыканием джампера бут должен работать всегда, даже если NAND девственно чист/загрузчик окирпичен. Главное после надевания джампера подать питание, нажать ресет. Скорее всего проблемой был плохой контакт джампера бут.

**Comment by ya-mouse** [comment]
Пробовал по-разному. Джампер надевал несколько раз (т.к. загружал в обычном режиме и проверял, что всё работает), сброс неоднократно нажимал, но уже после того, как подключал питание с воткнутой перемычкой. После обновления mboot каким-то чудесным образом всё завелось.
Т.е. если я случайно сотру mboot, то через edcl смогу восстановить его?
Есть ли где-то спецификации на К1879ХБ1Я и 1879ВЯ1Я ?
PS. Если бы не было контакта, то у меня должен был загружаться старый прошитый mboot, но он этого не делал.

**Comment by nekromant** [comment]
Когда одет джампер бут, загрузка mboot не должна происходить вообще. bootrom в этом режиме ожидает, что адрес куда прыгнуть будет записан по определенному адресу в памяти IM0. Ecdcl загружает в im0 копию загрузчика, и устанавливает этот указатель. Помимо него edcl также оставляет в памяти маркер, чтобы mboot запускался в slave режиме и исполнял команды, которые будут подсунуты ему по edcl. 

Вся логика загрузки по edcl описана в этом скрипте тут (см. метод run_code):

https://github.com/RC-MODULE/edcltool/blob/master/lib/fw.lua#L105
 
Для того, чтобы это корректно работало прошитый загрузчик не требуется. Могу только предположить, что по каким-то причинам (роутер/свитч/хаб?) аппаратура edcl не корректно поднимает линк, и запуск mboot с реинициализацией edcl это дело лечит. 

По поводу спецификаций и прочих документов необходимо отправить запрос в наш маркетинг. на 1879хб1я из-за hdmi оно доступно только под NDA. По поводу ВЯ1Я сказать ничего не могу.

**Comment by ya-mouse** [comment]
Подключение шнурком напрямую. Но вот что я точно заметил из странностей в tcpdump'e – некорректные checksum на всех пакетах от edcl (он же в raw-сокет пишет?). Как новый mboot может что-то лечить не совсем понятно – сброс же с джампером аппаратный (питание-то отключается). А что в bootrom? Он именно ROM или тоже перезаписываемый? А то без какой-либо спецификации SoC - просто чёрный ящик.
Загрузка mboot и не происходила, когда джампер был в замкнутом состоянии. Скрипт edcl затыкался после загрузки mboot-ued куда-то и надписи "Waiting for target board to respond". В tcpdump – пакеты с ошибкой контрольной суммы.

Скрипт видел. Из него вытаскивал команды на обновление mboot.

**Comment by nekromant** [comment]
ROM при производстве чипа закладывается, менять нельзя. 

Другой патчкорд пробовали? Судя по описанию либо залился в память битый образ, либо не записался корректно адрес прыжка, соответственно оно не стало исполнять код. Это либо phy, либо (более вероятно, так как их ). Если несильно надавить на микросхему phy поведение с оригинальным скриптом не меняется? Какая OS на хосте? 

Все, что было зашито изначально зашивалось именно через edcl, так что скорее всего проблема в окружении. 

После надевания джампера и подачи ресета первое что проверить надо - должен подняться линк, соответственно в dmesg на хосте информация об этом должна быть (поднялся как 10 мегабит или как 100?). Кнопку ресет после  подачи питания лучше нажать  на всякий случай. В случаях если втыкают "медленно" или разъем успел разболтаться микросхема ethernet phy может некорректно обработать poweron reset (очень редко, но бывает) 

Упрощенные доки есть тут: http://module.ru/mb7707/doc/ По поводу всей остальной документации надо отправлять запрос в маркетинг.

**Comment by ya-mouse** [comment]
После ручного обновления mboot я уже залил последнюю прошивку. Проверить не на чём.
Патч-корды, конечно же менял (и первый используется уже давно – проблем не было). После обновления и с первым патчем после обновления всё ок. Между попытками обновиться со старого, и ручным обновлением я патч уже не трогал. Какой линк был – не помню. Но он точно был. Плата была абсолютно новая – первые включения.
Было несколько попыток обновиться. Т.ч. заливка битого образа исключается. В последствии, тем же путём был залит rootfs на 100М+.
> $ md5sum mboot-uemd.bin
> 01297d1196b08e60146b29c03487d218  mboot-uemd.bin

Эти упрощённые доки я видел. Они уж очень упрощённые. Только memory map. Запрошу в маркетинге.

**Comment by ya-mouse** [comment]
> Если несильно надавить на микросхему phy поведение с оригинальным скриптом не меняется? 

Попробую посмотреть на осциллографе на соответствие IEEE по уровням (должно быть 950-1050мВ). Вот с этим уже как-то приходилось сталкиваться, когда раза в два уровень был ниже (но сеть работала).

**Comment by nekromant** [comment]
@ya-mouse Я сейчас, к сожалению, на больничном. Как доберусь до рабочего места, попрошу Вас запустить один edcl скрипт, с джампером и без.
